SERVICE_REGISTRY: dict[str, list[tuple[str, str, str, str]]] = {
    "s3": [("buckets", "s3", "list_buckets", "Buckets")],
    "sqs": [("queues", "sqs", "list_queues", "QueueUrls")],
    "sns": [("topics", "sns", "list_topics", "Topics")],
    "dynamodb": [("tables", "dynamodb", "list_tables", "TableNames")],
    "lambda": [("functions", "lambda", "list_functions", "Functions")],
    "iam": [
        ("roles", "iam", "list_roles", "Roles"),
        ("users", "iam", "list_users", "Users"),
        ("policies", "iam", "list_policies", "Policies"),
    ],
    "logs": [("log_groups", "logs", "describe_log_groups", "logGroups")],
    "ssm": [("parameters", "ssm", "describe_parameters", "Parameters")],
    "secretsmanager": [("secrets", "secretsmanager", "list_secrets", "SecretList")],
    "kinesis": [("streams", "kinesis", "list_streams", "StreamNames")],
    "events": [
        ("rules", "events", "list_rules", "Rules"),
        ("event_buses", "events", "list_event_buses", "EventBuses"),
    ],
    "ec2": [
        ("instances", "ec2", "describe_instances", "Reservations"),
        ("vpcs", "ec2", "describe_vpcs", "Vpcs"),
        ("subnets", "ec2", "describe_subnets", "Subnets"),
        ("security_groups", "ec2", "describe_security_groups", "SecurityGroups"),
        ("volumes", "ec2", "describe_volumes", "Volumes"),
    ],
    "route53": [("hosted_zones", "route53", "list_hosted_zones", "HostedZones")],
    "kms": [("keys", "kms", "list_keys", "Keys")],
    "cloudformation": [("stacks", "cloudformation", "list_stacks", "StackSummaries")],
    "stepfunctions": [("state_machines", "stepfunctions", "list_state_machines", "stateMachines")],
    "rds": [
        ("db_instances", "rds", "describe_db_instances", "DBInstances"),
        ("db_clusters", "rds", "describe_db_clusters", "DBClusters"),
    ],
    "ecs": [
        ("clusters", "ecs", "list_clusters", "clusterArns"),
        ("task_definitions", "ecs", "list_task_definitions", "taskDefinitionArns"),
    ],
    "monitoring": [
        ("alarms", "cloudwatch", "describe_alarms", "MetricAlarms"),
        ("dashboards", "cloudwatch", "list_dashboards", "DashboardEntries"),
    ],
    "ses": [("identities", "ses", "list_identities", "Identities")],
    "acm": [("certificates", "acm", "list_certificates", "CertificateSummaryList")],
    "wafv2": [("web_acls", "wafv2", "list_web_acls", "WebACLs")],
    "ecr": [("repositories", "ecr", "describe_repositories", "repositories")],
    "elasticache": [("cache_clusters", "elasticache", "describe_cache_clusters", "CacheClusters")],
    "glue": [
        ("databases", "glue", "get_databases", "DatabaseList"),
        ("crawlers", "glue", "get_crawlers", "Crawlers"),
    ],
    "athena": [("workgroups", "athena", "list_work_groups", "WorkGroups")],
    "apigateway": [("apis", "apigatewayv2", "get_apis", "Items")],
    "firehose": [("delivery_streams", "firehose", "list_delivery_streams", "DeliveryStreamNames")],
    "cognito-idp": [("user_pools", "cognito-idp", "list_user_pools", "UserPools")],
    "cognito-identity": [("identity_pools", "cognito-identity", "list_identity_pools", "IdentityPools")],
    "elasticmapreduce": [("clusters", "emr", "list_clusters", "Clusters")],
    "elasticloadbalancing": [("load_balancers", "elbv2", "describe_load_balancers", "LoadBalancers")],
    "elasticfilesystem": [("file_systems", "efs", "describe_file_systems", "FileSystems")],
    "cloudfront": [("distributions", "cloudfront", "list_distributions", "DistributionList")],
    "appsync": [("graphql_apis", "appsync", "list_graphql_apis", "graphqlApis")],
}

DESCRIBE_REGISTRY: dict[tuple[str, str], tuple[str, str, str, str | None]] = {
    ("s3", "buckets"): ("s3", "list_objects_v2", "Bucket", "Contents"),
    ("lambda", "functions"): ("lambda", "get_function", "FunctionName", None),
    ("ecs", "clusters"): ("ecs", "describe_clusters", "clusters", "clusters"),
    ("ecs", "task_definitions"): ("ecs", "describe_task_definition", "taskDefinition", "taskDefinition"),
    ("dynamodb", "tables"): ("dynamodb", "describe_table", "TableName", "Table"),
    ("rds", "db_instances"): ("rds", "describe_db_instances", "DBInstanceIdentifier", "DBInstances"),
    ("rds", "db_clusters"): ("rds", "describe_db_clusters", "DBClusterIdentifier", "DBClusters"),
    ("elasticache", "cache_clusters"): ("elasticache", "describe_cache_clusters", "CacheClusterId", None),
    ("sqs", "queues"): ("sqs", "get_queue_attributes", "QueueUrl", "Attributes"),
    ("sns", "topics"): ("sns", "get_topic_attributes", "TopicArn", "Attributes"),
    ("kinesis", "streams"): ("kinesis", "describe_stream", "StreamName", "StreamDescription"),
    ("firehose", "delivery_streams"): ("firehose", "describe_delivery_stream", "DeliveryStreamName", "DeliveryStreamDescription"),
    ("events", "rules"): ("events", "describe_rule", "Name", None),
    ("events", "event_buses"): ("events", "describe_event_bus", "Name", None),
    ("iam", "roles"): ("iam", "get_role", "RoleName", "Role"),
    ("iam", "users"): ("iam", "get_user", "UserName", "User"),
    ("iam", "policies"): ("iam", "get_policy", "PolicyArn", "Policy"),
    ("secretsmanager", "secrets"): ("secretsmanager", "describe_secret", "SecretId", None),
    ("kms", "keys"): ("kms", "describe_key", "KeyId", "KeyMetadata"),
    ("acm", "certificates"): ("acm", "describe_certificate", "CertificateArn", "Certificate"),
    ("cognito-idp", "user_pools"): ("cognito-idp", "describe_user_pool", "UserPoolId", "UserPool"),
    ("cognito-identity", "identity_pools"): ("cognito-identity", "describe_identity_pool", "IdentityPoolId", None),
    ("logs", "log_groups"): ("logs", "describe_log_groups", "logGroupNamePrefix", "logGroups"),
    ("ssm", "parameters"): ("ssm", "get_parameter", "Name", "Parameter"),
    ("cloudformation", "stacks"): ("cloudformation", "describe_stacks", "StackName", "Stacks"),
    ("stepfunctions", "state_machines"): ("stepfunctions", "describe_state_machine", "stateMachineArn", None),
    ("monitoring", "alarms"): ("cloudwatch", "describe_alarms", "AlarmNames", "MetricAlarms"),
    ("monitoring", "dashboards"): ("cloudwatch", "get_dashboard", "DashboardName", None),
    ("route53", "hosted_zones"): ("route53", "get_hosted_zone", "Id", "HostedZone"),
    ("cloudfront", "distributions"): ("cloudfront", "get_distribution", "Id", "Distribution"),
    ("elasticloadbalancing", "load_balancers"): ("elbv2", "describe_load_balancers", "LoadBalancerArns", "LoadBalancers"),
    ("ec2", "instances"): ("ec2", "describe_instances", "InstanceIds", "Reservations"),
    ("ec2", "vpcs"): ("ec2", "describe_vpcs", "VpcIds", "Vpcs"),
    ("ec2", "subnets"): ("ec2", "describe_subnets", "SubnetIds", "Subnets"),
    ("ec2", "security_groups"): ("ec2", "describe_security_groups", "GroupIds", "SecurityGroups"),
    ("ec2", "volumes"): ("ec2", "describe_volumes", "VolumeIds", "Volumes"),
    ("elasticfilesystem", "file_systems"): ("efs", "describe_file_systems", "FileSystemId", "FileSystems"),
    ("ecr", "repositories"): ("ecr", "describe_repositories", "repositoryNames", "repositories"),
    ("glue", "databases"): ("glue", "get_database", "Name", "Database"),
    ("glue", "crawlers"): ("glue", "get_crawler", "Name", "Crawler"),
    ("athena", "workgroups"): ("athena", "get_work_group", "WorkGroup", "WorkGroup"),
    ("apigateway", "apis"): ("apigatewayv2", "get_api", "ApiId", None),
    ("appsync", "graphql_apis"): ("appsync", "get_graphql_api", "apiId", "graphqlApi"),
    ("elasticmapreduce", "clusters"): ("emr", "describe_cluster", "ClusterId", "Cluster"),
}

METHOD_KWARGS: dict[tuple[str, str], dict] = {
    ("cognito-idp", "list_user_pools"): {"MaxResults": 60},
    ("cognito-identity", "list_identity_pools"): {"MaxResults": 60},
    ("wafv2", "list_web_acls"): {"Scope": "REGIONAL"},
}

PREFERRED_ID_FIELD: dict[tuple[str, str], str] = {
    ("route53", "hosted_zones"): "Id",
    ("events", "rules"): "Name",
    ("events", "event_buses"): "Name",
    ("wafv2", "web_acls"): "Name",
}

ID_FIELDS = [
    "BucketName",
    "FunctionName",
    "TableName",
    "TopicArn",
    "QueueUrl",
    "RoleName",
    "UserName",
    "PolicyName",
    "Arn",
    "PolicyArn",
    "logGroupName",
    "Name",
    "SecretName",
    "StreamName",
    "RuleName",
    "InstanceId",
    "VpcId",
    "SubnetId",
    "GroupId",
    "VolumeId",
    "HostedZoneId",
    "Id",
    "KeyId",
    "StackName",
    "stateMachineArn",
    "DBInstanceIdentifier",
    "DBClusterIdentifier",
    "clusterArn",
    "CertificateArn",
    "repositoryName",
    "CacheClusterId",
    "DeliveryStreamName",
    "WorkGroupName",
    "ApiId",
    "UserPoolId",
    "IdentityPoolId",
    "LoadBalancerArn",
    "FileSystemId",
    "AlarmName",
    "DashboardName",
    "CrawlerName",
    "DatabaseName",
    "DistributionId",
]

LIST_PARAMS = {
    "InstanceIds",
    "VpcIds",
    "SubnetIds",
    "GroupIds",
    "VolumeIds",
    "repositoryNames",
    "clusters",
    "AlarmNames",
    "LoadBalancerArns",
}

