rootProject.name = 'orderquestionnaire'

include ':modules:domain'
include ':modules:application'
include ':modules:adapters:out:mongo'
include ':modules:adapters:out:api-distribution'
include ':modules:bootstrap'

// Define caminhos físicos (opcional, mas recomendado)
project(':modules:domain').projectDir = file('modules/domain')
project(':modules:application').projectDir = file('modules/application')
project(':modules:adapters:out:mongo').projectDir = file('modules/adapters/out/mongo')
project(':modules:adapters:out:api-distribution').projectDir = file('modules/adapters/out/api-distribution')
project(':modules:bootstrap').projectDir = file('modules/bootstrap')

includeBuild('../shared')

