rootProject.name = 'hex-arch-template'

include(
        ':modules:domain:participantcatalog',
        ':modules:domain:personmdm',
        ':modules:domain:productcatalog',
        ':modules:application:personmdm'
)

includeBuild(
        'shared'
)
includeBuild(
        'observability'
)
includeBuild(
        'security-server'
)
includeBuild(
        'orderquestionnaire'
)
