plugins {
    id 'info.solidsoft.pitest'
}

group = 'com.acme.orderquestionnaire'

dependencies {
    implementation 'com.acme:shared'
    implementation 'com.acme:observability'
    implementation project(':modules:domain')

    testImplementation "com.tngtech.archunit:archunit:${archunitVersion}"
    testImplementation "com.tngtech.archunit:archunit-junit5:${archunitVersion}"
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}"
    testImplementation 'org.junit.platform:junit-platform-suite'
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            element = 'BUNDLE'

            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }

            limit {
                counter = 'BRANCH'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification

pitest {
    pitestVersion = '1.20.3'
    junit5PluginVersion = '1.2.1'

    targetClasses = [
            'com.acme.orderquestionnaire.application.question.*',
            'com.acme.orderquestionnaire.application.questionnaire.*'
    ]

    targetTests = [
            'com.acme.orderquestionnaire.application.question.*',
            'com.acme.orderquestionnaire.application.questionnaire.*',
            'com.acme.orderquestionnaire.application.FunctionalTest*'
    ]

    outputFormats = ['HTML', 'XML']
    timestampedReports = false
    failWhenNoMutations = true
    mutationThreshold = 60
    coverageThreshold = 65
}
