plugins {
    id 'info.solidsoft.pitest'
}

group = 'com.acme.orderquestionnaire'

dependencies {
    implementation 'com.acme:shared'
    implementation project(':modules:domain')

    testImplementation "com.tngtech.archunit:archunit:${archunitVersion}"
    testImplementation "com.tngtech.archunit:archunit-junit5:${archunitVersion}"
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}"
    testImplementation 'org.junit.platform:junit-platform-suite'
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            element = 'BUNDLE'

            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }

            limit {
                counter = 'BRANCH'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification