# docker/otel-collector/config.yml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls: { insecure: true }
  prometheus:
    endpoint: "0.0.0.0:9464"
  logging:
    loglevel: info

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  resource/local:
    attributes:
      - key: deployment.environment.name
        value: local
        action: upsert
      - key: service.namespace
        value: acme
        action: insert
  batch:
    timeout: 5s
    send_batch_size: 1024

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource/local, batch]
      exporters: [otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource/local, batch]
      exporters: [prometheus]

